### ISSUE TITLE
failure during the dart push with force enable to true

### ISSUE THREAD

**Issue by vincenzopalazzo** [k-paxian/dart-package-publisher#23]
I have the following action that I want to build with `force = true`, but I receive a failure https://github.com/zino-hofmann/graphql-flutter/runs/7099897390?check_suite_focus=true
```yaml
name: graphql Release Package

on:
  release:
    types: [created]
    tags:
      - graphql-v*
  push:
  workflow_run:
    workflows:
      - "graphql Test case"
      - "graphql Dart Code sanity check"
    branches: [ main ]
    types:
      - completed

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 # required!

      - name: 'publish graphql to to Pub.dev'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: false
          skipTests: true
          force: true
          dryRunOnly: ${{ github.event_name != 'release' }}
          relativePath: './packages/graphql/'
```
