### ISSUE TITLE
Don't use the "name" input field, instead create a separate one

### ISSUE THREAD

**Issue by pavanpodila** [k-paxian/dart-package-publisher#3]
> This is more of an aesthetic suggestion but can greatly improve the usability of the action when viewing the progress on the Actions page of Github.

Instead of relying on the `name` field for the package name, use a separate field, say `packageName` to capture the name of the package. The `name` field is used by Github to print the name of the action, which is a more user-friendly way of reading the step. 

![image](https://user-images.githubusercontent.com/156846/72982049-35b3f980-3e04-11ea-8b70-a6089377bb93.png)

Notice in the above picture, the name of the package is the only one that shows up, which makes it difficult to know what the step is doing.

**Comment by k-paxian** [comment]
You can completely omit the `name` yourself, it's totally up to you to use it.
like this will work as well:
```yml
  - uses: k-paxian/dart-package-publisher@master
    with:
      accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
      refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
```

If you want to describe this step put a descriptive `name`

```yml
  - name: '>> Publish My Dart package <<'
    uses: k-paxian/dart-package-publisher@master
    with:
      accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
      refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
```
