### ISSUE TITLE
Change Repo from master to main

### ISSUE THREAD

**Issue by pranilshah4024** [k-paxian/dart-package-publisher#31]
- Github Action File :

```yaml
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Format code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.FLUTTER_DEVICE_IMEI_SECRET }}
          flutter: true
          skipTests: true
```

### **The Issue ( typically occurs in GitHub Actions when the workflow is trying to reference origin/master, but the branch doesn’t exist or isn't fetched properly.): till few months back it was working fine but today I ran into this issue ** 

```console
Run k-paxian/dart-package-publisher@v[1](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:1).5.1
  with:
    credentialJson: ***
    flutter: true
    skipTests: true
    dryRunOnly: false
    testRunOnly: false
    suppressBuildRunner: false
    format: false
    force: false
    flutterBranch: stable
  env:
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.19.6-x64
    PUB_CACHE: /home/runner/.pub-cache
/usr/bin/docker run --name c1ea41[2](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:2)c1c771746e7a5881ca628c811b7_c96fbb --label 7168c1 --workdir /github/workspace --rm -e "FLUTTER_ROOT" -e "PUB_CACHE" -e "INPUT_CREDENTIALJSON" -e "INPUT_FLUTTER" -e "INPUT_SKIPTESTS" -e "INPUT_ACCESSTOKEN" -e "INPUT_REFRESHTOKEN" -e "INPUT_RELATIVEPATH" -e "INPUT_DRYRUNONLY" -e "INPUT_TESTRUNONLY" -e "INPUT_SUPPRESSBUILDRUNNER" -e "INPUT_FORMAT" -e "INPUT_FORCE" -e "INPUT_FLUTTERBRANCH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/flutter_device_imei/flutter_device_imei":"/github/workspace" 7168c1:ea412c1c771746e7a5881ca628c811b7
Check inputs...
OK
Package dir: /github/workspace
Because flutter_device_imei requires the Flutter SDK, version solving failed.

Flutter users should use `flutter pub` instead of `dart pub`.
Flutter package detected. Installing Flutter from stable branch...
Cloning into '/flutter'...
Updating files:  76% (11282/14694)
Updating files:  77% (11[3](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:3)15/14694)
Updating files:  78% (11[4](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:4)62/14694)
Updating files:  79% (11609/14694)
Updating files:  80% (117[5](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:5)6/14694)
Updating files:  81% (11903/14[6](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:6)94)
Updating files:  82% (12050/14694)
Updating files:  83% (1219[7](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:7)/14694)
Updating files:  [8](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:8)4% (12343/14694)
Updating files:  85% (124[9](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:9)0/14694)
Updating files:  86% (12637/14694)
Updating files:  87% (12784/14694)
Updating files:  88% (12931/14694)
Updating files:  89% (13078/14694)
Updating files:  90% (13225/14694)
Updating files:  91% (13372/14694)
Updating files:  92% (13519/14694)
Updating files:  93% (13666/14694)
Updating files:  94% (13813/14694)
Updating files:  95% (13960/14694)
Updating files:  96% (14[10](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:10)7/14694)
Updating files:  97% (14254/14694)
Updating files:  98% ([14](https://github.com/pranilshah4024/flutter_device_imei/actions/runs/13336490804/job/37252782814#step:9:14)401/14694)
Updating files:  99% (14548/14694)
Updating files: 100% (14694/14694)
Updating files: 100% (14694/14694), done.
fatal: Not a valid object name origin/master
fatal: Not a valid object name origin/master
```

**Comment by k-paxian** [comment]
you can try to use different flutter branch,
https://github.com/k-paxian/dart-package-publisher?tab=readme-ov-file#flutterbranch 
it's stable by default, but it seems it's not very stable

**Comment by pranilshah4024** [comment]
@k-paxian Thanks for the prompt reply, getting the same error with this setup too

        name: Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.FLUTTER_DEVICE_IMEI_SECRET }}
          flutter: true
          skipTests: true
          flutterBranch: main

**Comment by k-paxian** [comment]
This literally means that this command
https://github.com/k-paxian/dart-package-publisher/blob/0f91081ddade3d182efa59dbdf9c6804d9c214a1/entrypoint.sh#L55
is not properly working with your setup it would be 
```
git clone -b main --depth 1 https://github.com/flutter/flutter.git /flutter
```

Does this command alone works for you?

**Comment by pranilshah4024** [comment]
There are no issues on my local machine, but when I'm publishing it using GitHub actions, this issue occurs.

the GitHub version used by instance is `git version 2.48.1`

**Comment by k-paxian** [comment]
I've got an idea of a GitHub agent actually caching /flutter folder between runs. This might explain why it's failing to clone flutter over existing copy which is still assuming that origin/master exist.

I'd probably add /flutter folder cleanup before cloning the repo.

**Comment by Shahroz16** [comment]
Hey guys, is there any update here?

**Comment by pranilshah4024** [comment]
@k-paxian can you please make that fix and release a new version or something?

**Comment by k-paxian** [comment]
For context another failed run https://github.com/fluttercandies/flutter_hsvcolor_picker/actions/runs/13372896171/job/37345338894

**Comment by k-paxian** [comment]
Also Flutter seems to still have `master` as default branch 🤷 

![Image](https://github.com/user-attachments/assets/39a865f6-6b38-4599-bfd5-4081ce3ac34a)

**Comment by Shahroz16** [comment]
@k-paxian it might solve if we were to specify version? 🤔 

https://github.com/flutter/flutter/issues/163198

**Comment by k-paxian** [comment]
Well the recent test run also 💚  https://github.com/k-paxian/dart-package-publisher/actions/runs/13433489965/job/37530392670

**Comment by k-paxian** [comment]
All in all that's a Flutter fault. We just cloning it nothing special here

**Comment by k-paxian** [comment]
@pranilshah4024 

Side note:

```yaml
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Format code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
```

You actually don't need any of this, the action is already doing exactly that internally

**Comment by Shahroz16** [comment]
@k-paxian for the last run did you do something different to get it to green? 

```
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-flutter

    - name: dry-run publishing to feel confident deployment will work after merging PR
      uses: k-paxian/dart-package-publisher@v1.6
      with:
        credentialJson: ${{ secrets.CREDENTIAL_JSON }}
        dryRunOnly: true 
        flutter: true
        flutterBranch: master
```

its giving me this error

https://github.com/customerio/customerio-flutter/actions/runs/13433744729/job/37531233696?pr=204

The current Flutter SDK version is 0.0.0-unknown.
Because customer_io requires Flutter SDK version >=2.5.0, version solving failed.
You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.29.0. 
Failed to update packages.
